### ISSUE TITLE
Possible Search Result Issue

### ISSUE THREAD

**Issue by KidSquid1** [opensmarthouse/opensmarthouse-web#10]
I entered the model number of a Jasco/GE wall switch - “45709” and the following is the results page

![image](https://user-images.githubusercontent.com/28264840/89051849-755f1f00-d31a-11ea-945b-9560c79b49f3.png)

It shows “0” devices found, yet shows details of what looks to be an unrelated device on the right.

**Comment by cdjackson** [comment]
As discussed on the forum, this is correct. There are no devices in the database with this label etc, and there are no devices found. Devices are listed in the list below the search box. When you mouse-over one of the search results, the detailed data is shown in the right pane. The information you see in the right pane now is presumably from a previous search.

I could clear this when there's a search - this might be a good idea to avoid confusion, but otherwise this all looks normal to me.

**Comment by KidSquid1** [comment]
`right pane now is presumably from a previous search`

I did not place any other searches....the search for the 45709 was the only one.

**Comment by bwosborne2** [comment]
I believe just hovering over an item populates the right pane.

**Comment by cdjackson** [comment]
As Bruce said - hovering over the list that was there previously will populate this details panel. 

> I did not place any other searches

No - but the system starts off displaying ALL devices, so there is already a search filled in. We could start by displaying NO devices, but I think that's counterintuitive isn't it?

I'm pretty sure that you will have run your mouse over a line in the table, and that will have populated the details pane. The details pane was not cleared when you made a new search, and this led to the confusion.

Does that make sense?  Shall we close this or am I still missing something?

**Comment by bwosborne2** [comment]
Verified it clears now.

**Comment by cdjackson** [comment]
@KidSquid1 do we close this? I think it's just a misunderstanding of how it works, and I think by clearing the details box it should be clearer now?

WDYT?

**Comment by KidSquid1** [comment]
Hello -

Sorry for the slow response...had to do a bit of traveling.

Yes, now that the panel clears when doing a search the area of confusion is gone.  

Thanks for making the adjustment.

Squid
