### ISSUE TITLE
Adding devices does not work

### ISSUE THREAD

**Issue by sihui62** [opensmarthouse/opensmarthouse-web#5]
Adding devices does not work, not in Firefox, not in Chrome.
After hitting the "Save changes" button nothing happens, no error message.

![grafik](https://user-images.githubusercontent.com/10405486/88481470-02415b80-cf5c-11ea-967f-57c95cd37eb7.png)

**Comment by sihui62** [comment]
Ahh, it is there:

https://opensmarthouse.org/zwavedatabase/1274

But the dialog does not close after hitting the "Save changes" button.

**Comment by bwosborne2** [comment]
I noticed that when I got the xml import working. 
Some files were missed and our troubleshooting debug log location had changed in the reorganization.

**Comment by cdjackson** [comment]
@bwosborne2 I think this might be an issue with the return from the script - there is currently no return. It does seem to return success (200), but there is no data and I'm wondering if that's causing the problem. I just checked that the site is set for the dialog to close, and I've also added a toast to say success (I'll add one for failure too) and neither of these things happen.

Can you take a look to see what happens if you maybe just return `[]` or something?

**Comment by bwosborne2** [comment]
Can you take a look to see what happens if you maybe just return [] or something?

I just return after possibly sending the email. What do you wish me to send?

**Comment by cdjackson** [comment]
Just try adding “return ‘{}';” and see what happens...

**Comment by bwosborne2** [comment]
Done (fixing the single quotes)

**Comment by cdjackson** [comment]
Ok, after much messing around, I've got this to work.  What was needed is to use `echo` to get it to return the '{}'.

My thinking is we might want to better handle errors in here by returning some sort of json string or something when there is an error. The UI now presents a toast if there's an error, and presents a success toast when it works (well, I assumed it works - it closes the dialog ;) ) but I'm thinking a bit more feedback when things go wrong might be useful.

**Comment by cdjackson** [comment]
I think this is now resolved so I'll close. If I've missed something, please yell...
